import { ERROR_DISPLAY_AREAS, ERROR_DISPLAY_SEVERITY } from "./error-display-types";

export const ERROR_DISPLAY_CATALOG = {
  unsupported_runtime: { area: ERROR_DISPLAY_AREAS.SYSTEM, severity: ERROR_DISPLAY_SEVERITY.BLOCKED, title: "Unsupported runtime", message: "This preview runtime does not provide required desktop APIs.", cause: "Browser/static preview has no approved local write support.", nextAction: "Use supported desktop runtime for local save/report preparation.", blocking: true },
  invalid_plan: { area: ERROR_DISPLAY_AREAS.LOCAL_WRITE_BOUNDARY, severity: ERROR_DISPLAY_SEVERITY.BLOCKED, title: "Local write plan invalid", message: "Local save plan did not pass boundary validation.", cause: "Required paths or payload plans are missing/invalid.", nextAction: "Prepare all plans, then rebuild local write boundary.", blocking: true },
  partial_failure: { area: ERROR_DISPLAY_AREAS.LOCAL_PERSISTENCE, severity: ERROR_DISPLAY_SEVERITY.ERROR, title: "Partial save failure", message: "Some files were written but others were skipped or failed.", cause: "Runtime write operations returned mixed outcomes.", nextAction: "Review validation and retry save after fixing blocked entries.", blocking: false },
  storage_unavailable: { area: ERROR_DISPLAY_AREAS.SETTINGS_PERSISTENCE, severity: ERROR_DISPLAY_SEVERITY.WARNING, title: "Settings storage unavailable", message: "Safe settings could not be persisted in this runtime.", cause: "localStorage/desktop storage is unavailable or denied.", nextAction: "Continue with defaults, or switch runtime with storage support.", blocking: false },
  missing_session: { area: ERROR_DISPLAY_AREAS.SESSION, severity: ERROR_DISPLAY_SEVERITY.BLOCKED, title: "Missing session", message: "Session metadata is required before preparing/saving logs.", cause: "Session has not been started.", nextAction: "Start session, then prepare preview plans.", blocking: true },
  missing_log_plans: { area: ERROR_DISPLAY_AREAS.LOG_SCAFFOLD, severity: ERROR_DISPLAY_SEVERITY.BLOCKED, title: "Missing preview plans", message: "One or more required preview plans are not prepared.", cause: "session/comments/alerts/stream-state/report plan is incomplete.", nextAction: "Prepare missing preview plans before report/save.", blocking: true },
  native_readonly_unavailable: { area: ERROR_DISPLAY_AREAS.OBS_DIAGNOSTICS, severity: ERROR_DISPLAY_SEVERITY.WARNING, title: "Native read-only unavailable", message: "Native read-only diagnostics are unavailable in this runtime.", cause: "WebSocket is unavailable in browser/static preview.", nextAction: "Use mock mode (safe default) or run supported runtime.", blocking: false },
  mock_mode_active: { area: ERROR_DISPLAY_AREAS.OBS_CONNECTION, severity: ERROR_DISPLAY_SEVERITY.INFO, title: "Mock OBS active", message: "Mock OBS mode is active and safe by default.", cause: "Default mode for non-desktop preview/testing.", nextAction: "Continue testing safely, or switch to native read-only diagnostics.", blocking: false },
  password_not_saved: { area: ERROR_DISPLAY_AREAS.SETTINGS_PERSISTENCE, severity: ERROR_DISPLAY_SEVERITY.INFO, title: "OBS password is not saved", message: "OBS password is never persisted by design.", cause: "Safe settings policy excludes credentials.", nextAction: "Enter password at runtime only when needed.", blocking: false },
  validation_error: { area: ERROR_DISPLAY_AREAS.LOCAL_WRITE_BOUNDARY, severity: ERROR_DISPLAY_SEVERITY.ERROR, title: "Validation error", message: "Validation found issues in local write boundary inputs.", cause: "Boundary checks found unsafe or incomplete plan entries.", nextAction: "Fix listed validation issues and rebuild boundary plan.", blocking: false },
  save_blocked: { area: ERROR_DISPLAY_AREAS.LOCAL_PERSISTENCE, severity: ERROR_DISPLAY_SEVERITY.BLOCKED, title: "Save blocked", message: "Saving is currently blocked by runtime or boundary checks.", cause: "Unsupported runtime or unresolved boundary validation.", nextAction: "Resolve blocking checks, then save again.", blocking: true },
  report_not_ready: { area: ERROR_DISPLAY_AREAS.REPORT_GENERATION, severity: ERROR_DISPLAY_SEVERITY.WARNING, title: "Report not ready", message: "Report generation inputs are incomplete.", cause: "Missing session and/or required preview plans.", nextAction: "Prepare missing inputs, then regenerate report output plan.", blocking: false },
};
