const sampleComments=[];
const radarOrder=["question","audio_issue","video_issue","danger","highlight","general"];
const state={mode:"raw",session:null,comments:[],alerts:[],streamState:[],reportMarkdown:"",reportJson:null,parseWarnings:[],sourcesByFile:{}};
const byId=(id)=>document.querySelector(`#${id}`);
const pick=(o,ks)=>ks.map((k)=>o?.[k]).find((v)=>v!==undefined&&v!==null&&v!=="");
const fmt=(v)=>v===undefined||v===null||v===""?"Not available":String(v);
function redactSecrets(text){return String(text).replace(/(streamKey|password|token)\s*[:=]\s*[^\s,]+/gi,'$1=[redacted]').replace(/key=[^\s&]+/gi,'key=[redacted]').replace(/rtmps?:\/\/([^/\s]+)\/([^\s]+)/gi,'rtmp://$1/[redacted]');}
function detectSmartLiveSource(input){const raw=String(pick(input,["appEdition","source"])||pick(input?.session||{},["appEdition","source"])||pick(input?.report||{},["source"])||"").toLowerCase(); if(raw.includes('obs')) return 'obs-bridge'; if(raw.includes('pc')) return 'pc-standalone'; if(raw.includes('mobile')||raw.includes('android')) return 'mobile-android'; if(raw.includes('sample')) return 'sample'; return 'unknown';}
function normalizeSession(input){return {sessionId:pick(input,["sessionId","session_id","id"]),appEdition:pick(input,["appEdition"]),source:detectSmartLiveSource(input),createdAt:pick(input,["createdAt","startedAt"]),startedAt:pick(input,["startedAt","createdAt"]),endedAt:pick(input,["endedAt","stoppedAt"]),stoppedAt:pick(input,["stoppedAt","endedAt"]),mode:pick(input,["mode"]),status:pick(input,["status"]),commentsCount:pick(input,["commentsCount","totalComments"]),alertsCount:pick(input,["alertsCount","totalAlerts"]),reportGeneratedAt:pick(input,["reportGeneratedAt"]),raw:input};}
function normalizeComment(input,lineNumber){const labelsRaw=Array.isArray(input.labels)?input.labels:[pick(input,["label","category","classification"])||"general"]; let labels=labelsRaw.map((x)=>String(x).toLowerCase()); if(input.held||labels.includes('url_detected')||labels.includes('suspicious')) labels.push('danger'); labels=labels.map((l)=>radarOrder.includes(l)?l:(['url_detected','suspicious','danger'].includes(l)?'danger':'general')); return {lineNumber,timestamp:pick(input,["timestamp","createdAt"]),author:pick(input,["author","displayName","user"]),displayName:pick(input,["displayName","author","user"]),message:redactSecrets(pick(input,["message","text","body"])),text:redactSecrets(pick(input,["text","message","body"])),labels:[...new Set(labels)],held:Boolean(input.held),priority:pick(input,["priority","severity"]),source:detectSmartLiveSource(input),raw:input};}
function normalizeAlert(input,lineNumber){return {lineNumber,timestamp:pick(input,["timestamp"]),type:pick(input,["type","category"]),severity:pick(input,["severity","level"]),message:redactSecrets(pick(input,["message"])),source:detectSmartLiveSource(input),raw:input};}
function normalizeStreamState(input,lineNumber){return {lineNumber,timestamp:pick(input,["timestamp"]),source:detectSmartLiveSource(input),appEdition:pick(input,["appEdition"]),connectionState:pick(input,["connectionState"]),streamState:pick(input,["streamState","state"]),currentScene:pick(input,["currentScene","currentSceneName","sceneName"]),streamActive:pick(input,["streamActive"]),recordingActive:pick(input,["recordingActive"]),droppedFrames:pick(input,["droppedFrames"]),outputSkippedFrames:pick(input,["outputSkippedFrames","skippedFrames"]),cpuUsage:pick(input,["cpuUsage","cpuUsagePercent"]),memoryUsage:pick(input,["memoryUsage","memoryUsagePercent"]),raw:input};}
function normalizeReportJson(input){return {source:detectSmartLiveSource(input),generatedAt:pick(input,["generatedAt","createdAt"]),session:pick(input,["session","sessionId"]),commentSummary:pick(input,["commentSummary"]),radarGroups:pick(input,["radarGroups"]),alerts:pick(input,["alerts","totalAlerts"]),raw:input};}
function parseJsonObject(raw,label){ let v; try { v=JSON.parse(raw); } catch (error) { throw new Error(`${label} parse error: ${error.message}`); } if(!v||Array.isArray(v)||typeof v!== 'object') throw new Error(`${label} must be a JSON object.`); return v;}
function renderJsonlItems(rawText,normalizer,label){const parsed=[]; const invalidLines=[]; rawText.split(/\r?\n/).forEach((line,i)=>{if(!line.trim())return; try{parsed.push(normalizer(JSON.parse(line),i+1));}catch{invalidLines.push(i+1);}}); if(invalidLines.length) state.parseWarnings.push(`${label} invalid lines: ${invalidLines.join(', ')}`); return parsed;}
function parseJsonl(rawText,normalizer,label){return renderJsonlItems(rawText,normalizer,label);}
function parseCommentsJsonl(rawText){return parseJsonl(rawText,normalizeComment,'comments.jsonl');}
function setChecklist(f,s){const li=document.querySelector(`#fileChecklist li[data-file-key="${f}"] .check-status`); if(li) li.textContent=s;}
function renderList(id,items,mapper){const root=byId(id); root.replaceChildren(...(items.length?items.map(mapper):[Object.assign(document.createElement('p'),{textContent:'No data loaded.'})]));}
function renderWarnings(){renderList('parseWarningsPanel',state.parseWarnings,(w)=>Object.assign(document.createElement('li'),{textContent:w,className:w.toLowerCase().includes('error')?'err':'warn'}));}
function renderSummary(){const sources=Object.values(state.sourcesByFile).filter(Boolean); const detected=sources[0]||'unknown'; const mixed=[...new Set(sources)].length>1; byId('detectedSource').textContent=detected; byId('mixedSourceWarning').textContent=mixed?'mixed-source warning: loaded files appear to come from different editions.':''; const dl=byId('sourceCompatibilitySummary'); const rows=[["detected appEdition/source",detected],["loaded comments count",state.comments.length],["loaded alerts count",state.alerts.length],["loaded stream-state count",state.streamState.length],["report status",state.reportJson||state.reportMarkdown?"loaded":"missing"],["parse warnings count",state.parseWarnings.length]]; dl.replaceChildren(...rows.flatMap(([k,v])=>{const dt=document.createElement('dt');dt.textContent=k;const dd=document.createElement('dd');dd.textContent=fmt(v);return [dt,dd];}));}
function renderAll(){renderSummary(); renderWarnings(); const session=byId('sessionSummary'); session.replaceChildren(); if(state.session){for(const [k,v] of Object.entries(state.session)){if(k==='raw')continue; const dt=document.createElement('dt');dt.textContent=k; const dd=document.createElement('dd');dd.textContent=fmt(v); session.append(dt,dd);} } renderComments(); renderList('alertsJsonlList',state.alerts,(a)=>Object.assign(document.createElement('p'),{textContent:`${fmt(a.timestamp)} ${fmt(a.type)} ${fmt(a.severity)} ${fmt(a.message)}`})); renderList('streamStateJsonlList',state.streamState,(s)=>Object.assign(document.createElement('p'),{textContent:`${fmt(s.timestamp)} | ${fmt(s.source)}/${fmt(s.appEdition)} | ${fmt(s.connectionState)||fmt(s.streamState)} | scene:${fmt(s.currentScene)} | active:${fmt(s.streamActive)} rec:${fmt(s.recordingActive)} cpu:${fmt(s.cpuUsage)} mem:${fmt(s.memoryUsage)}`})); byId('reportMarkdownPreview').textContent=redactSecrets(state.reportMarkdown||'No report.md loaded yet.'); const r=byId('reportJsonSummary'); r.replaceChildren(); if(state.reportJson){for(const [k,v] of Object.entries(state.reportJson)){if(k==='raw')continue; const dt=document.createElement('dt');dt.textContent=k; const dd=document.createElement('dd');dd.textContent=fmt(typeof v==='object'?JSON.stringify(v):v); r.append(dt,dd);} }}
function renderComments(){const list=byId('commentList'); if(state.mode==='raw'){renderList('commentList',state.comments,(c)=>Object.assign(document.createElement('p'),{textContent:`${fmt(c.timestamp)} ${fmt(c.displayName)}: ${fmt(c.message)} [${c.labels.join(',')}]`})); return;} const grouped=Object.fromEntries(radarOrder.map((k)=>[k,[]])); state.comments.forEach((c)=>{const key=c.labels.find((l)=>radarOrder.includes(l))||'general'; grouped[key].push(c);}); list.replaceChildren(...radarOrder.map((k)=>{const sec=document.createElement('section'); const h=document.createElement('h3');h.textContent=`${k} (${grouped[k].length})`; sec.append(h,...grouped[k].map((c)=>Object.assign(document.createElement('p'),{textContent:`${fmt(c.timestamp)} ${fmt(c.displayName)}: ${fmt(c.message)}`}))); return sec;}));}
function loadSet(files){state.parseWarnings=[]; try{state.session=normalizeSession(parseJsonObject(files.session,'session.json')); setChecklist('session.json','Loaded'); state.sourcesByFile['session.json']=state.session.source;}catch(e){state.parseWarnings.push(`session.json error: ${e.message}`); setChecklist('session.json','Error');}
try{state.comments=parseCommentsJsonl(files.comments||''); setChecklist('comments.jsonl','Loaded'); state.sourcesByFile['comments.jsonl']=state.comments[0]?.source||'unknown';}catch(e){state.parseWarnings.push(`comments.jsonl error: ${e.message}`); setChecklist('comments.jsonl','Error');}
try{state.alerts=parseJsonl(files.alerts||'',normalizeAlert,'alerts.jsonl'); setChecklist('alerts.jsonl','Loaded'); state.sourcesByFile['alerts.jsonl']=state.alerts[0]?.source||'unknown';}catch(e){state.parseWarnings.push(`alerts.jsonl error: ${e.message}`); setChecklist('alerts.jsonl','Error');}
try{state.streamState=parseJsonl(files.streamState||'',normalizeStreamState,'stream-state.jsonl'); setChecklist('stream-state.jsonl','Loaded'); state.sourcesByFile['stream-state.jsonl']=state.streamState[0]?.source||'unknown';}catch(e){state.parseWarnings.push(`stream-state.jsonl error: ${e.message}`); setChecklist('stream-state.jsonl','Error');}
state.reportMarkdown=files.reportMd||''; setChecklist('report.md',files.reportMd?'Loaded':'Pending');
try{state.reportJson=normalizeReportJson(parseJsonObject(files.reportJson,'report.json')); setChecklist('report.json','Loaded'); state.sourcesByFile['report.json']=state.reportJson.source;}catch(e){state.parseWarnings.push(`report.json error: ${e.message}`); setChecklist('report.json','Error');}
renderAll();}
const sample=(src)=>({session:JSON.stringify({sessionId:`${src}-1`,appEdition:src,source:src,startedAt:'2026-05-20T10:00:00Z',status:'ok',commentsCount:2,alertsCount:1}),comments:'{"timestamp":"10:01","displayName":"A","message":"question?","labels":["question"],"source":"'+src+'"}\n{"timestamp":"10:02","displayName":"B","message":"runtime value hidden","labels":["url_detected"],"held":true,"source":"'+src+'"}',alerts:'{"timestamp":"10:03","type":"audio","severity":"warn","message":"runtime value redacted","source":"'+src+'"}',streamState:'{"timestamp":"10:04","connectionState":"connected","streamState":"live","currentScene":"Main","streamActive":true,"recordingActive":false,"cpuUsage":22,"memoryUsage":44,"source":"'+src+'","appEdition":"'+src+'"}',reportMd:'# report\nruntime endpoint redacted',reportJson:JSON.stringify({source:src,generatedAt:'2026-05-20T10:05:00Z',session:{id:'x'},commentSummary:{},radarGroups:{},alerts:1})});
byId('loadObsBridgeSampleButton')?.addEventListener('click',()=>{loadSet(sample('obs-bridge'));byId('dataSourceState').textContent='Loaded OBS Bridge sample';});
byId('loadPcStandaloneSampleButton')?.addEventListener('click',()=>{loadSet(sample('pc-standalone'));byId('dataSourceState').textContent='Loaded PC Standalone sample';});
byId('loadMobileAndroidSampleButton')?.addEventListener('click',()=>{loadSet(sample('mobile-android'));byId('dataSourceState').textContent='Loaded Mobile Android sample';});
byId('loadSampleDataButton')?.addEventListener('click',()=>{loadSet(sample('sample'));byId('dataSourceState').textContent='Loaded generic bundled sample';});
document.querySelectorAll('.tab').forEach((t)=>t.addEventListener('click',()=>{state.mode=t.dataset.mode;document.querySelectorAll('.tab').forEach((x)=>x.classList.toggle('active',x===t));renderComments();}));
function bindSessionLoader() {byId('sessionFileInput')?.addEventListener('change',async(e)=>{const f=e.target.files?.[0];if(!f)return; loadSet({...sample('unknown'),session:await f.text()});});}
function bindCommentsLoader() {byId('commentsFileInput')?.addEventListener('change',async(e)=>{const f=e.target.files?.[0];if(!f)return; loadSet({...sample('unknown'),comments:await f.text()});});}
function bindAlertsLoader() {byId('alertsFileInput')?.addEventListener('change',async(e)=>{const f=e.target.files?.[0];if(!f)return; loadSet({...sample('unknown'),alerts:await f.text()});});}
function bindStreamStateLoader() {byId('streamStateFileInput')?.addEventListener('change',async(e)=>{const f=e.target.files?.[0];if(!f)return; loadSet({...sample('unknown'),streamState:await f.text()});});}
function bindReportMarkdownLoader() {byId('reportMarkdownFileInput')?.addEventListener('change',async(e)=>{const f=e.target.files?.[0];if(!f)return; loadSet({...sample('unknown'),reportMd:await f.text()});});}
function bindReportJsonLoader() {byId('reportJsonFileInput')?.addEventListener('change',async(e)=>{const f=e.target.files?.[0];if(!f)return; loadSet({...sample('unknown'),reportJson:await f.text()});});}
bindSessionLoader();
bindCommentsLoader();
bindAlertsLoader();
bindStreamStateLoader();
bindReportMarkdownLoader();
bindReportJsonLoader();
loadSet(sample('obs-bridge'));
byId('dataSourceState').textContent='Loaded OBS Bridge sample';

function setMode(mode){ state.mode=mode; renderComments(); }
function renderRaw(){ setMode("raw"); }
function renderRadar(){ setMode("radar"); }
function renderReport(){ renderAll(); }

function renderRawOrRadar(){ renderComments(); }

// Error: parse/load errors are surfaced via parseWarnings.