import { t, getLanguage, setLanguage } from './i18n.js';

const app = document.querySelector('#app');
if (!app) throw new Error('PC Standalone app root not found.');

const saved = JSON.parse(localStorage.getItem('pcStandaloneSettings') || '{}');
const state = {
  screen: 'Live',
  commentMode: 'Raw',
  language: getLanguage(),
  localSettings: { rtmpUrl: saved.rtmpUrl || '' },
  streamKey: '',
  selectedComment: 1,
  comments: [
    { time: '12:28:31', author: 'takebon', handle: '@takebon_live', radar: 'warning', category: 'Audio/video trouble', message: 'Audio may be a little quiet.', status: 'unread' },
    { time: '12:28:40', author: 'yuuki', handle: '@yuuki_q', radar: 'question', category: 'Questions', message: 'Can this be used from a phone too?', status: 'pinned' },
    { time: '12:28:55', author: 'sakura', handle: '@sakura_fan', radar: 'praise', category: 'Hype', message: 'Looks good. Looking forward to the stream.', status: 'done' },
    { time: '12:29:10', author: 'ops_bot', handle: '@ops_monitor', radar: 'issue', category: 'Audio/video trouble', message: 'Minor frame jitter detected.', status: 'unread' }
  ]
};
const navItems = ['Live', 'Prepare', 'Comments', 'Stability', 'Settings', 'Report'];
const el = (tag, txt, cls) => { const n = document.createElement(tag); if (cls) n.className = cls; if (txt !== undefined) n.textContent = txt; return n; };
const commentsOrdered = () => state.commentMode === 'Raw' ? [...state.comments] : [...state.comments].sort((a,b)=>({warning:0,question:1,issue:2,general:2,praise:3}[a.radar]??9)-({warning:0,question:1,issue:2,general:2,praise:3}[b.radar]??9));
const safeDownload = (filename, text) => { const blob = new Blob([text], { type: 'application/json;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = filename; document.body.append(a); a.click(); a.remove(); URL.revokeObjectURL(url); };
const languageToggle = () => { const lang = el('div', undefined, 'row lang-toggle'); lang.append(el('span', t('language'))); [['en', t('english')], ['ja', t('japanese')]].forEach(([code, label]) => { const b = el('button', label, state.language === code ? 'active' : ''); b.onclick = () => { setLanguage(code); state.language = code; render(); }; lang.append(b); }); return lang; };

function buildCommentsPanel() { const wrap = el('section', undefined, 'panel comments-panel'); const top = el('div', undefined, 'comments-top'); top.append(el('h3', t('comments')), el('span', t('viewerCount'), 'viewer-chip')); wrap.append(top); const tabs = el('div', undefined, 'tabs'); ['Raw', 'Radar'].forEach((m) => { const b = el('button', m, state.commentMode === m ? 'active' : ''); b.onclick = () => { state.commentMode = m; render(); }; tabs.append(b); }); wrap.append(tabs); const list = el('div', undefined, 'comment-list'); commentsOrdered().forEach((c) => { const it = el('article', undefined, `comment ${c.radar}`); const meta = el('div', undefined, 'comment-meta'); meta.append(el('small', c.time), el('strong', c.author), el('span', c.category, 'category')); it.append(meta, el('p', c.message)); list.append(it); }); wrap.append(list); return wrap; }

function liveScreen() { const area = el('section', undefined, 'main'); const grid = el('div', undefined, 'live-grid'); const left = el('div', undefined, 'stack'); const panel = el('section', undefined, 'panel'); const preview = el('div', undefined, 'preview-surface'); preview.append(el('span', 'PREVIEW', 'badge red'), el('span', 'LIVE', 'badge green')); panel.append(preview); left.append(panel); grid.append(left, buildCommentsPanel()); area.append(grid); return area; }

function prepareScreen(){
  const m=el('section',undefined,'main'); const g=el('section',undefined,'panel dense');
  g.append(el('h2',t('prepare')));
  const steps=el('div',undefined,'steps'); ['Source','Platform','Video / Audio','Details','Check'].forEach((s,i)=>steps.append(el('span',s,i===1?'step active':'step'))); g.append(el('h3','Setup steps'),steps);
  const src=el('div',undefined,'card-grid'); [['🖥','Screen','Full desktop capture','recommended'],['🪟','Window','Single app capture','optional'],['📷','Camera','Webcam feed','available'],['🎙','Mic only','Audio-only stream','optional']].forEach(([i,t1,d,b])=>{const c=el('article',undefined,'subcard');c.append(el('strong',`${i} ${t1}`),el('p',d),el('span',b,'pill'));src.append(c);}); g.append(el('h3','Source selection'),src);
  const pf=el('div',undefined,'card-grid'); [['YouTube','connected'],['Twitch','not connected'],['Custom RTMP','selected']].forEach(([n,s])=>{const c=el('article',undefined,'subcard');c.append(el('strong',n),el('p',s));pf.append(c);}); g.append(el('h3','Platform selection'),pf);
  const form=el('article',undefined,'subcard'); form.append(el('strong','Stream details')); ['Stream title','Category','Language','Mature content','Short note'].forEach((k)=>{const i=el('input'); i.placeholder=k; form.append(i);}); g.append(form);
  const rt=el('article',undefined,'subcard'); rt.append(el('strong','RTMP target')); const r=el('input');r.placeholder='RTMP / RTMPS URL';r.value=state.localSettings.rtmpUrl;r.oninput=()=>{state.localSettings.rtmpUrl=r.value;localStorage.setItem('pcStandaloneSettings',JSON.stringify({rtmpUrl:r.value}));}; const k=el('input');k.type='password';k.placeholder=t('runtimeStreamKey');k.oninput=()=>{state.streamKey='';}; rt.append(r,k,el('p',t('streamKeyNotSaved')),el('button',t('validateLocal')),el('span','Validation status: mock')); g.append(rt);
  const ci=el('article',undefined,'subcard'); ci.append(el('strong','Comment integration'),el('p','YouTube comments ON / Twitch OFF / Custom chat not connected / Raw default')); g.append(ci);
  const rec=el('article',undefined,'subcard'); rec.append(el('strong','Ready for preview'),el('div',undefined,'preview-mini'),el('p','Mic meter / System audio meter / 720p 30fps / Stable preset recommended'),el('button','Apply recommended settings'),el('button',t('openPreview'))); g.append(rec);
  m.append(g); return m;
}

function commentsScreen(){ const m=el('section',undefined,'main'); const w=el('section',undefined,'panel'); w.append(el('h2',t('comments'))); const head=el('div',undefined,'toolbar'); ['Raw','Radar','All','Questions','Audio/video trouble','Hype','Held / risky'].forEach((x)=>head.append(el('button',x,state.commentMode===x?'active':''))); const s=el('input');s.placeholder='Search';head.append(s,el('button','Filter')); w.append(head); const grid=el('div',undefined,'comments-grid'); const list=el('div',undefined,'comment-list'); commentsOrdered().forEach((c,i)=>{const it=el('article',undefined,`comment ${c.radar} ${state.selectedComment===i?'selected':''}`); it.onclick=()=>{state.selectedComment=i;render();}; it.append(el('div',`${c.time}  ${c.author} ${c.handle}`,'comment-meta'),el('p',c.message),el('small',`${c.category} • ${c.status}`)); list.append(it);}); const detail=el('aside',undefined,'subcard'); const sel=commentsOrdered()[state.selectedComment]||state.comments[0]; detail.append(el('h3','Selected comment'),el('p',`${sel.author} ${sel.handle}`),el('p',`First comment: 12:10 / Count: 14 / Likes: 27`),el('p',sel.message),el('span',sel.category,'pill')); ['Read aloud','Pin','Mark done','Hide comment','Mute user'].forEach((a)=>detail.append(el('button',a))); grid.append(list,detail); w.append(grid); const foot=el('div',undefined,'toolbar'); ['Read queue: 3','Filter','NG settings','Selected: 1','Prev','Next'].forEach((x)=>foot.append(el('button',x))); w.append(foot); m.append(w); return m; }

function stabilityScreen(){ const m=el('section',undefined,'main'); const p=el('section',undefined,'panel dense'); p.append(el('h2',t('stability'))); const sum=el('div',undefined,'card-grid'); [['Audio issue','1','warning'],['Network unstable','2','warning'],['Dropped frames','3.2%','caution'],['CPU high load','92%','danger']].forEach(([a,b,c])=>{const x=el('article',undefined,'subcard');x.append(el('strong',a),el('p',`${b} • ${c} • last 15 min`));sum.append(x);}); p.append(el('h3','Alert summary'),sum); const al=el('article',undefined,'subcard'); al.append(el('h3','Active alerts')); ['Mic volume fluctuated','Network jitter detected','Dropped frames increased','CPU usage is high'].forEach((x)=>al.append(el('p',`12:3x • ${x} • warning ▸`))); p.append(al); const rec=el('article',undefined,'subcard highlight'); rec.append(el('h3','Stability mode recommended'),el('p','Image impact low / latency impact low / viewer experience improved'),el('p','4500→3500 kbps, 60→30 fps, BGM -4dB, keyframe 2s→4s'),el('button',t('switchToStabilityMode')),el('button',t('reassessLater')),el('button',t('openDetailedSettings'))); p.append(rec); m.append(p); return m; }

function settingsScreen(){ const m=el('section',undefined,'main'); const p=el('section',undefined,'panel dense'); p.append(el('h2',t('settings'))); const tabs=el('div',undefined,'tabs'); ['Stream settings','Input settings','Display settings','Comment settings','Read-aloud settings','Stability settings'].forEach((x,i)=>tabs.append(el('button',x,i===0?'active':''))); p.append(tabs); ['Stream settings','Input settings','Display settings','Comment settings','Read-aloud settings','Stability settings'].forEach((title)=>{const c=el('article',undefined,'subcard');c.append(el('h3',title),el('p','Mock controls and toggles for desktop workflow.'));if(title==='Stream settings')c.append(el('p',t('streamKeyNotSaved')));p.append(c);}); const b=el('div',undefined,'toolbar'); ['Import settings','Export settings','Reset to defaults','Cancel','Save'].forEach((x)=>b.append(el('button',x))); p.append(b,languageToggle()); m.append(p); return m; }

function reportScreen(){ const m=el('section',undefined,'main'); const p=el('section',undefined,'panel dense'); p.append(el('h2',t('report'))); const met=el('div',undefined,'card-grid'); [['Stream duration','01:12:24'],['Average viewers','98'],['Peak viewers','186'],['Comments','247'],['Questions','52'],['Trouble count','9']].forEach(([k,v])=>{const c=el('article',undefined,'subcard');c.append(el('strong',k),el('p',v));met.append(c);}); p.append(el('h3','Summary metric cards'),met); const charts=el('div',undefined,'card-grid'); ['Bitrate','Dropped frames','Cumulative comments','Alert count'].forEach((x)=>{const c=el('article',undefined,'subcard');c.append(el('strong',x),el('div',undefined,'chart'));charts.append(c);}); p.append(charts); const t1=el('article',undefined,'subcard');t1.append(el('h3','Highlight candidates'));['product feature explanation','demo start','summary section','Q&A session'].forEach((r)=>t1.append(el('p',`${r} • Create clip`))); const t2=el('article',undefined,'subcard');t2.append(el('h3','Trouble history'));['bitrate drop','dropped frames','network unstable','comment delay'].forEach((r)=>t2.append(el('p',`${r} • Add memo`))); p.append(t1,t2); const e=el('div',undefined,'toolbar'); const a=el('button',t('downloadReport'));a.onclick=()=>safeDownload('report.json',JSON.stringify({duration:'01:12:24'},null,2)); const b=el('button',t('downloadLogs'));b.onclick=()=>safeDownload('logs.json',JSON.stringify([{message:'local preview'}],null,2)); const d=el('button',t('downloadComments'));d.onclick=()=>safeDownload('comments.jsonl',state.comments.map((x)=>JSON.stringify(x)).join('\n')); e.append(a,b,d); p.append(e); m.append(p); return m; }

function renderMain(){if(state.screen==='Live')return liveScreen();if(state.screen==='Prepare')return prepareScreen();if(state.screen==='Comments')return commentsScreen();if(state.screen==='Stability')return stabilityScreen();if(state.screen==='Settings')return settingsScreen();return reportScreen();}
function render(){ app.textContent=''; const shell=el('main',undefined,'shell'); const header=el('header',undefined,'topbar'); header.append(el('h1','SmartLive PC Standalone')); const chips=el('div',undefined,'header-chips'); ['Platform: YouTube',`${t('streamStatus')}: Preview`,'00:18:42',`${t('preset')}: ${t('stableMode')}`].forEach((x)=>chips.append(el('span',x,'chip'))); const right=el('div',undefined,'top-actions'); right.append(languageToggle(),el('button',t('openPreview')),el('button','End preview','danger')); header.append(chips,right); shell.append(header); const body=el('div',undefined,'body'); const side=el('aside',undefined,'sidebar'); const nav = el('div', undefined, 'nav'); navItems.forEach((n)=>{const b=el('button',t(n.toLowerCase()),state.screen===n?'active':'');b.onclick=()=>{state.screen=n;render();};nav.append(b);}); side.append(nav); body.append(side,renderMain()); shell.append(body); app.append(shell);} render();
