import { t, getLanguage, setLanguage } from './i18n.js';
import { createInitialState, orderComments, validateRtmpTarget, sanitizePersistedSettings, buildSafeReportExport, buildSafeLogsExport, buildSafeCommentsJsonl, buildSafeSettingsExport, assertNoSecretsInExport, applyCommentAction, applyPrepareSelection, applyStabilityAction } from './behavior.js';
const app = document.querySelector('#app'); if (!app) throw new Error('PC Standalone app root not found.');
const PERSIST_KEY = 'pcStandaloneSettings';
let mediaStream = null;
const state = createInitialState(getLanguage());
Object.assign(state.prepare, sanitizePersistedSettings(JSON.parse(localStorage.getItem(PERSIST_KEY) || '{}')));
Object.assign(state.settings, sanitizePersistedSettings(JSON.parse(localStorage.getItem(PERSIST_KEY) || '{}')));
const el=(t,x,c)=>{const n=document.createElement(t); if(c) n.className=c; if(x!==undefined) n.textContent=x; return n;};
const persist=()=>localStorage.setItem(PERSIST_KEY, JSON.stringify(sanitizePersistedSettings({ ...state.prepare, ...state.settings })));
const log=(action,status)=>state.logs.push({ timestamp:new Date().toISOString(), action, status });
const visibleComments=()=>orderComments(state.comments,state.commentMode).filter((c)=>!c.hidden).slice(0,state.settings.maxComments);
const selected=()=>state.comments.find((c)=>c.id===state.selectedComment)||visibleComments()[0]||state.comments[0];
const download=(name,text)=>{assertNoSecretsInExport(text);const a=el('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;document.body.append(a);a.click();a.remove();};
async function openPreview(){ state.preview.status='previewing'; state.preview.errorMessage=''; state.preview.source=state.prepare.selectedSource; state.preview.startedAt=new Date().toISOString(); try{ if(!navigator.mediaDevices) throw new Error('media API unavailable'); if(state.preview.source==='Screen'||state.preview.source==='Window') mediaStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false}); else if(state.preview.source==='Camera') mediaStream=await navigator.mediaDevices.getUserMedia({video:true,audio:false}); else mediaStream=await navigator.mediaDevices.getUserMedia({audio:true,video:false}); }catch(e){ state.preview.errorMessage=`Preview fallback: ${/denied|permission/i.test(String(e))?'permission denied':'media API unavailable'}`; } log('open-preview',state.preview.errorMessage||'ok'); render(); }
function endPreview(){ (mediaStream?.getTracks?.()||[]).forEach((t)=>t.stop()); mediaStream=null; state.preview.status='stopped'; log('end-preview','stopped'); render(); }
function render(){ app.textContent=''; const shell=el('main',undefined,'shell'); const h=el('header',undefined,'topbar'); h.append(el('h1','SmartLive PC Standalone')); const chips=el('div',undefined,'header-chips'); ['Platform: '+state.prepare.selectedPlatform,`Stream status: ${state.preview.status}`,'Preset: '+state.prepare.selectedPreset].forEach((x)=>chips.append(el('span',x,'chip'))); const acts=el('div',undefined,'top-actions'); const lang=el('div',undefined,'row'); [['en','English'],['ja','日本語']].forEach(([k,v])=>{const b=el('button',v,state.language===k?'active':'');b.onclick=()=>{setLanguage(k);state.language=k;render();};lang.append(b);}); const op=el('button',t('openPreview')); op.onclick=openPreview; const ed=el('button','End preview','danger'); ed.onclick=endPreview; acts.append(lang,op,ed); h.append(chips,acts); shell.append(h);
const body=el('div',undefined,'body'); const side=el('aside',undefined,'sidebar'); ['Live','Prepare','Comments','Stability','Settings','Report'].forEach((n)=>{const b=el('button',n,state.screen===n?'nav-btn active':'nav-btn'); b.onclick=()=>{state.screen=n;render();}; side.append(b);}); side.append(el('p',state.stability.stabilityMode?'Stability mode ON':'Stable')); body.append(side);
const main=el('section',undefined,'main');
if(state.screen==='Prepare'){ main.append(el('h2','Prepare')); ['Screen','Window','Camera','Mic only'].forEach((v)=>{const b=el('button',v,state.prepare.selectedSource===v?'active':'');b.onclick=()=>{applyPrepareSelection(state,'selectedSource',v);persist();render();};main.append(b);}); ['YouTube','Twitch','Custom RTMP'].forEach((v)=>{const b=el('button',v,state.prepare.selectedPlatform===v?'active':'');b.onclick=()=>{applyPrepareSelection(state,'selectedPlatform',v);persist();render();};main.append(b);}); ['Stable','Balanced','High quality','Low latency'].forEach((v)=>{const b=el('button',v,state.prepare.selectedPreset===v?'active':'');b.onclick=()=>{applyPrepareSelection(state,'selectedPreset',v);persist();render();};main.append(b);}); const in1=el('input');in1.placeholder='stream title';in1.value=state.prepare.streamTitle;in1.oninput=()=>state.prepare.streamTitle=in1.value; const url=el('input');url.placeholder='RTMP URL';url.value=state.prepare.rtmpUrl;url.oninput=()=>state.prepare.rtmpUrl=url.value; const key=el('input'); key.type='password'; key.placeholder=t('runtimeStreamKey'); const vb=el('button',t('validateSetup')); vb.onclick=()=>{state.prepare.validationStatus=validateRtmpTarget(state.prepare.rtmpUrl); key.value=''; persist(); render();}; main.append(in1,url,key,el('p','Stream key is not saved'),vb,el('p','Validation status: '+state.prepare.validationStatus)); }
if(state.screen==='Live'){ main.append(el('h2','Live')); const p=el('div',undefined,'preview-surface'); p.append(el('p',state.preview.status==='previewing'?'Preview running':state.preview.status),el('p','Source: '+state.prepare.selectedSource)); if(state.preview.errorMessage) p.append(el('p',state.preview.errorMessage)); const v=el('video'); v.autoplay=true; v.muted=true; if(mediaStream&&mediaStream.getVideoTracks().length) v.srcObject=mediaStream; p.append(v); main.append(p); if(state.settings.showCommentPanel){ const tb=el('div'); ['Raw','Radar'].forEach((m)=>{const b=el('button',m,state.commentMode===m?'active':'');b.onclick=()=>{state.commentMode=m;render();};tb.append(b);}); main.append(tb); visibleComments().forEach((c)=>{const r=el('button',`${c.author}: ${c.message} ${(c.pinned?'Pinned ':'')}${(c.done?'Done ':'')}${(c.muted?'Muted ':'')}`,state.selectedComment===c.id?'active':'');r.onclick=()=>{state.selectedComment=c.id;render();};main.append(r);}); } }
if(state.screen==='Comments'){ main.append(el('h2','Comments')); ['Raw','Radar'].forEach((m)=>{const b=el('button',m,state.commentMode===m?'active':'');b.onclick=()=>{state.commentMode=m;state.settings.defaultCommentTab=m;persist();render();};main.append(b);}); visibleComments().forEach((c)=>{const r=el('button',`${c.author}: ${c.message}`,state.selectedComment===c.id?'active':'');r.onclick=()=>{state.selectedComment=c.id;render();};main.append(r);}); const s=selected(); main.append(el('p','Read queued: '+(s?.read?'Yes':'No'))); [['Read aloud','read'],['Pin','pin'],['Mark done','done'],['Hide comment','hide'],['Mute user','mute']].forEach(([l,a])=>{const b=el('button',l);b.onclick=()=>{if(l==='Read aloud'&&!state.settings.readAloudEnabled){state.report.statusMessage='Read-aloud disabled'; render(); return;} applyCommentAction(state,s.id,a); if(a==='hide'&&state.selectedComment===s.id){state.selectedComment=visibleComments()[0]?.id||state.comments[0]?.id;} render();};main.append(b);}); }
if(state.screen==='Stability'){ main.append(el('h2','Stability')); const b1=el('button',t('switchToStabilityMode')); b1.onclick=()=>{applyStabilityAction(state,'switch');persist();render();}; const b2=el('button',t('reassessLater')); b2.onclick=()=>{applyStabilityAction(state,'reassess');render();}; const b3=el('button',t('openDetailedSettings')); b3.onclick=()=>{state.screen='Settings'; state.settings.activeSettingsTab='Stability settings'; render();}; main.append(b1,b2,b3,el('p',`Reassess count: ${state.stability.reassessCount}`),el('p',state.stability.lastAction)); }
if(state.screen==='Settings'){ main.append(el('h2','Settings')); ['Stream settings','Input settings','Display settings','Comment settings','Read-aloud settings','Stability settings'].forEach((t1)=>{const b=el('button',t1,state.settings.activeSettingsTab===t1?'active':''); b.onclick=()=>{state.settings.activeSettingsTab=t1; render();}; main.append(b);}); main.append(el('p','Settings saved locally')); const show=el('button',`show comment panel: ${state.settings.showCommentPanel?'ON':'OFF'}`); show.onclick=()=>{state.settings.showCommentPanel=!state.settings.showCommentPanel; render();}; const mr=el('input'); mr.value=String(state.settings.maxComments); mr.oninput=()=>{state.settings.maxComments=Math.max(1,Number(mr.value)||1);}; main.append(show,mr); [['Save',()=>{persist();state.report.statusMessage='Settings saved locally';render();}],['Reset to defaults',()=>{const n=createInitialState(state.language);state.prepare=n.prepare;state.settings={...n.settings,activeSettingsTab:state.settings.activeSettingsTab};state.commentMode=n.commentMode;persist();state.report.statusMessage='Settings reset locally';render();}],['Export settings',()=>download('settings.json',JSON.stringify(buildSafeSettingsExport(state),null,2))],['Import settings',()=>{state.report.statusMessage='Import settings mock complete';render();}],['Cancel',()=>{state.report.statusMessage='Cancel local changes';render();}]].forEach(([l,f])=>{const b=el('button',l);b.onclick=f; main.append(b);}); main.append(el('p',state.report.statusMessage||'')); }
if(state.screen==='Report'){ main.append(el('h2','Report')); [['Download report.json',()=>download('report.json',JSON.stringify(buildSafeReportExport(state),null,2))],['Download logs.json',()=>download('logs.json',JSON.stringify(buildSafeLogsExport(state),null,2))],['Download comments.jsonl',()=>download('comments.jsonl',buildSafeCommentsJsonl(state))]].forEach(([l,f])=>{const b=el('button',l);b.onclick=f;main.append(b);}); }
body.append(main); shell.append(body); app.append(shell);
}
render();
